eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: SecondEurekaClient

server:
  port: 9091

